# Generated by Django 3.0.2 on 2020-10-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('PostalAddress', models.TextField()),
                ('AboutCompany', models.TextField()),
                ('sector', models.CharField(choices=[('Automobile', 'Automobile'), ('Banking/Financial Services/Insurance', 'Banking/Financial Services Insurance'), ('Conglomerate', 'Conglomerate'), ('Consulting', 'Consulting'), ('Consumer Durables', 'Consumer Durables'), ('Engineering', 'Engineering'), ('FMCG', 'FMCG'), ('Government/PSU', 'Government/PSU'), ('Healthcare & Pharma', 'Healthcare & Pharma'), ('Infrastructure', 'Infrastructure'), ('IT & ITES', 'IT & ITES'), ('Leasure,Travel & Tourism', 'Leasure,Travel & Tourism'), ('Manufacturing', 'Manufacturing'), ('Market Research', 'Market Research'), ('Media & Advertising', 'Media & Advertising'), ('Power/Oil/Energy', 'Power/Oil/Energy'), ('R & D', 'R & D'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Semiconductor', 'Semiconductor'), ('Telecom', 'Telecom')], default=None, max_length=100)),
                ('JobDescription', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('JobStatus', models.CharField(choices=[('Internship Only', 'Internship Only'), ('Fulltime Only', 'Fulltime Only'), ('Fulltime + Internship', 'Fulltime + Internship')], default=None, max_length=100)),
                ('Bond_service_agreement', models.CharField(max_length=100)),
                ('Company_website', models.CharField(max_length=10)),
                ('Registartion_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestMode', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default=None, max_length=100)),
                ('Aptitude', models.BooleanField()),
                ('Coding', models.BooleanField()),
                ('Communication', models.BooleanField()),
                ('GD', models.BooleanField()),
                ('Techinacal', models.BooleanField()),
                ('HR', models.BooleanField()),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Head.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSLC', models.PositiveIntegerField(default=0)),
                ('PUC', models.PositiveIntegerField(default=0)),
                ('UG', models.PositiveIntegerField(default=0)),
                ('PG', models.PositiveIntegerField(default=0)),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Head.Company')),
            ],
        ),
    ]
