# Generated by Django 3.0.2 on 2020-10-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Head', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='AboutCompany',
            new_name='About_Company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Bond_service_agreement',
            new_name='Bond_or_serviceAgreement',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='CompanyName',
            new_name='Company_Name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='JobDescription',
            new_name='Job_Description',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='JobStatus',
            new_name='Job_Status',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='PostalAddress',
            new_name='Postal_Address',
        ),
        migrations.RenameField(
            model_name='criteria',
            old_name='CompanyName',
            new_name='Company_Name',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='CompanyName',
            new_name='Company_Name',
        ),
        migrations.AlterField(
            model_name='test',
            name='TestMode',
            field=models.CharField(choices=[('Online', 'ONLINE'), ('Offline', 'OFFLINE')], default=None, max_length=100),
        ),
    ]
