# Generated by Django 3.0.5 on 2020-10-25 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Head', '0003_auto_20201024_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='Status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='Job_Status',
            field=models.CharField(choices=[('Internship Only', 'Internship Only'), ('Fulltime Only', 'Fulltime Only'), ('Fulltime + Internship', 'Fulltime + Internship')], default='Fulltime Only', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('Automobile', 'Automobile'), ('Banking/Financial Services/Insurance', 'Banking/Financial Services Insurance'), ('Conglomerate', 'Conglomerate'), ('Consulting', 'Consulting'), ('Consumer Durables', 'Consumer Durables'), ('Engineering', 'Engineering'), ('FMCG', 'FMCG'), ('Government/PSU', 'Government/PSU'), ('Healthcare & Pharma', 'Healthcare & Pharma'), ('Infrastructure', 'Infrastructure'), ('IT & ITES', 'IT & ITES'), ('Leasure,Travel & Tourism', 'Leasure,Travel & Tourism'), ('Manufacturing', 'Manufacturing'), ('Market Research', 'Market Research'), ('Media & Advertising', 'Media & Advertising'), ('Power/Oil/Energy', 'Power/Oil/Energy'), ('R & D', 'R & D'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Semiconductor', 'Semiconductor'), ('Telecom', 'Telecom'), ('Other', 'Other')], default='IT & ITES', max_length=100),
        ),
    ]
