# Generated by Django 3.1.2 on 2020-11-04 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100)),
                ('Postal_Address', models.TextField()),
                ('About_Company', models.TextField()),
                ('sector', models.CharField(choices=[('Automobile', 'Automobile'), ('Banking/Financial Services/Insurance', 'Banking/Financial Services Insurance'), ('Conglomerate', 'Conglomerate'), ('Consulting', 'Consulting'), ('Consumer Durables', 'Consumer Durables'), ('Engineering', 'Engineering'), ('FMCG', 'FMCG'), ('Government/PSU', 'Government/PSU'), ('Healthcare & Pharma', 'Healthcare & Pharma'), ('Infrastructure', 'Infrastructure'), ('IT & ITES', 'IT & ITES'), ('Leasure,Travel & Tourism', 'Leasure,Travel & Tourism'), ('Manufacturing', 'Manufacturing'), ('Market Research', 'Market Research'), ('Media & Advertising', 'Media & Advertising'), ('Power/Oil/Energy', 'Power/Oil/Energy'), ('R & D', 'R & D'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Semiconductor', 'Semiconductor'), ('Telecom', 'Telecom'), ('Other', 'Other')], default='IT & ITES', max_length=100)),
                ('Job_Description', models.TextField()),
                ('Position', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Job_Status', models.CharField(choices=[('Internship Only', 'Internship Only'), ('Fulltime Only', 'Fulltime Only'), ('Fulltime + Internship', 'Fulltime + Internship')], default='Fulltime Only', max_length=100)),
                ('Bond_or_serviceAgreement', models.CharField(max_length=100)),
                ('Company_website', models.CharField(max_length=100)),
                ('Registartion_link', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=50)),
                ('package', models.CharField(max_length=100)),
                ('stipend', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('Tier1', 'Tier1'), ('Tier2', 'Tier2'), ('Tier3', 'Tier3')], default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestMode', models.CharField(choices=[('Online', 'ONLINE'), ('Offline', 'OFFLINE')], default=None, max_length=100)),
                ('Test_Date', models.DateField()),
                ('Aptitude', models.BooleanField()),
                ('Coding', models.BooleanField()),
                ('Communication', models.BooleanField()),
                ('GD', models.BooleanField()),
                ('Techinacal', models.BooleanField()),
                ('HR', models.BooleanField()),
                ('Company_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drives.company')),
            ],
        ),
        migrations.CreateModel(
            name='drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selected_status', models.BooleanField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Company_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drives.company')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSLC', models.PositiveIntegerField(default=0)),
                ('PUC', models.PositiveIntegerField(default=0)),
                ('UG', models.PositiveIntegerField(default=0)),
                ('PG', models.PositiveIntegerField(default=0)),
                ('Company_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drives.company')),
            ],
        ),
    ]
