# Generated by Django 3.1.2 on 2020-11-06 19:41

import Drives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Date',
        ),
        migrations.AddField(
            model_name='company',
            name='Year',
            field=models.IntegerField(default=Drives.models.current_year),
        ),
    ]
