# Generated by Django 3.0.2 on 2020-11-01 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Drives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selected_status', models.BooleanField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Company_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drives.Company')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
