# Generated by Django 3.1.2 on 2020-11-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drives', '0002_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Company_website',
            field=models.CharField(max_length=100),
        ),
    ]
