# Generated by Django 3.1.2 on 2020-11-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drives', '0002_auto_20201107_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='Selected_status',
            field=models.IntegerField(default=0),
        ),
    ]
