# Generated by Django 3.1.2 on 2020-11-28 20:34

import Drives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drives', '0003_auto_20201127_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Year',
            field=models.CharField(default=Drives.models.current_year, max_length=100),
        ),
    ]
