# Generated by Django 3.1.2 on 2020-11-28 20:47

import Drives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drives', '0004_auto_20201129_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Year',
            field=models.IntegerField(default=Drives.models.current_year),
        ),
    ]
