# Generated by Django 3.1.2 on 2020-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drives', '0006_auto_20201201_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Test_Date',
            field=models.DateField(),
        ),
    ]
