# Generated by Django 3.0.5 on 2020-10-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20201022_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='semester',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='5', max_length=10),
        ),
    ]
