# Generated by Django 3.0.5 on 2020-10-22 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0005_auto_20201022_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(choices=[('SSLC', 'SSLC'), ('PUC', 'PUC'), ('DEGREE', 'DEGREE'), ('MCA', 'MCA')], max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('yearOfPass', models.IntegerField()),
                ('CGPA', models.DecimalField(decimal_places=2, max_digits=4)),
                ('markscard', models.ImageField(null=True, upload_to='markscard/')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='mca_table',
            name='username',
        ),
        migrations.RemoveField(
            model_name='puc_table',
            name='username',
        ),
        migrations.RemoveField(
            model_name='sslc_table',
            name='username',
        ),
        migrations.DeleteModel(
            name='Degree_table',
        ),
        migrations.DeleteModel(
            name='MCA_table',
        ),
        migrations.DeleteModel(
            name='PUC_table',
        ),
        migrations.DeleteModel(
            name='SSLC_table',
        ),
    ]
