# Generated by Django 3.0.5 on 2020-10-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20201023_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_table',
            name='markscard',
            field=models.ImageField(blank=True, null=True, upload_to='markscard/'),
        ),
    ]
