# Generated by Django 3.0.5 on 2020-10-31 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_auto_20201023_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='batch',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
