# Generated by Django 3.0.5 on 2020-10-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_student_profile_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='batch',
            field=models.PositiveIntegerField(),
        ),
    ]
