# Generated by Django 3.0.2 on 2020-11-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_auto_20201031_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/'),
        ),
    ]
