# Generated by Django 3.1.2 on 2020-11-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_student_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='editStatus',
            field=models.IntegerField(default=0),
        ),
    ]
