# Generated by Django 3.1.2 on 2020-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_student_profile_editstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='bloodGroup',
            field=models.CharField(choices=[('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O-', 'O-'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-')], default='O+', max_length=10),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='currentAddress',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='hobbies',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='knownLanguages',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='permanentAddress',
            field=models.TextField(null=True),
        ),
    ]
