# Generated by Django 3.1.2 on 2020-11-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_auto_20201123_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_profile',
            old_name='course',
            new_name='courseName',
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='bloodGroup',
            field=models.CharField(default='O+', max_length=10),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='semester',
            field=models.CharField(default='5', max_length=10),
        ),
    ]
