# Generated by Django 3.1.2 on 2020-11-26 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_auto_20201123_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_table',
            name='updateAcademic',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academic_table',
            name='courses',
            field=models.CharField(max_length=50),
        ),
    ]
