# Generated by Django 3.1.2 on 2020-11-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_auto_20201126_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic_table',
            old_name='updateAcademic',
            new_name='qualification',
        ),
    ]
