# Generated by Django 3.1.2 on 2020-11-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_auto_20201126_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
