# Generated by Django 3.0.2 on 2020-12-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_auto_20201205_2215'),
        ('Student', '0018_auto_20201130_1405'),
    ]

    operations = [
    ]
