# Generated by Django 3.1.2 on 2020-11-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='view_Status',
            field=models.IntegerField(default=0),
        ),
    ]
